import i18next from 'i18next'
import { initReactI18next, useTranslation } from 'react-i18next'

export const languages = [
  { code: 'en', label: 'English', direction: 'ltr' },
  { code: 'fr', label: 'Français', direction: 'ltr' },
  { code: 'es', label: 'Español', direction: 'ltr' },
  { code: 'pt', label: 'Português', direction: 'ltr' },
  { code: 'de', label: 'Deutsch', direction: 'ltr' },
  { code: 'it', label: 'Italiano', direction: 'ltr' },
  { code: 'nl', label: 'Nederlands', direction: 'ltr' },
  { code: 'ru', label: 'Русский', direction: 'ltr' },
  { code: 'uk', label: 'Українська', direction: 'ltr' },
  { code: 'pl', label: 'Polski', direction: 'ltr' },
  { code: 'tr', label: 'Türkçe', direction: 'ltr' },
  { code: 'ar', label: 'العربية', direction: 'rtl' },
  { code: 'zh-CN', label: '简体中文', direction: 'ltr' },
  { code: 'zh-TW', label: '繁體中文', direction: 'ltr' },
  { code: 'ja', label: '日本語', direction: 'ltr' },
  { code: 'ko', label: '한국어', direction: 'ltr' },
  { code: 'hi', label: 'हिन्दी', direction: 'ltr' },
  { code: 'id', label: 'Bahasa Indonesia', direction: 'ltr' },
  { code: 'vi', label: 'Tiếng Việt', direction: 'ltr' },
  { code: 'th', label: 'ไทย', direction: 'ltr' },
  { code: 'bn', label: 'বাংলা', direction: 'ltr' },
  { code: 'ro', label: 'Română', direction: 'ltr' },
  { code: 'el', label: 'Ελληνικά', direction: 'ltr' },
  { code: 'sk', label: 'Slovenčina', direction: 'ltr' },
  { code: 'zu', label: 'isiZulu', direction: 'ltr' },
] as const

export type LanguageCode = typeof languages[number]['code']

const english = {
  'nav.home': 'Home', 'nav.signIn': 'Sign in', 'nav.createAccount': 'Create account',
  'nav.dashboard': 'Dashboard', 'nav.connectWallet': 'Connect wallet', 'nav.staking': 'Staking',
  'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Roadmap', 'nav.transactions': 'Transactions',
  'nav.myNodes': 'My nodes', 'nav.profile': 'Profile', 'nav.settings': 'Settings',
  'nav.logout': 'Log out', 'nav.workspace': 'Workspace', 'common.loading': 'Loading...',
  'common.save': 'Save', 'common.saving': 'Saving...', 'common.cancel': 'Cancel', 'common.editProfile': 'Edit profile',
  'common.copy': 'Copy', 'common.copied': 'Copied', 'common.fullName': 'Full name',
  'common.emailAddress': 'Email address', 'common.password': 'Password', 'common.confirmPassword': 'Confirm password',
  'profile.accountOverview': 'Account overview', 'profile.personalInformation': 'Personal information',
  'profile.currentEmail': 'Current email', 'profile.verified': 'Verified', 'profile.notVerified': 'Not verified',
  'profile.changeEmail': 'Change email address', 'profile.newEmail': 'New email address',
  'profile.currentPassword': 'Current password', 'profile.sendConfirmation': 'Send confirmation',
  'profile.addPhoto': 'Add photo', 'profile.changePhoto': 'Change photo', 'profile.removePhoto': 'Remove photo',
  'profile.referralId': 'Referral ID', 'settings.appearance': 'Appearance', 'settings.sound': 'Sound',
  'settings.soundEffects': 'Sound effects', 'settings.volume': 'Volume', 'settings.notifications': 'Notifications',
  'settings.security': 'Security', 'settings.twoFactor': 'Two-factor authentication',
  'settings.enableTwoFactor': 'Enable two-factor authentication', 'settings.disableTwoFactor': 'Disable two-factor authentication',
  'settings.recoveryCodes': 'Recovery codes', 'settings.language': 'Language', 'settings.currency': 'Currency',
  'settings.dark': 'Dark', 'settings.light': 'Light', 'settings.system': 'System',
} satisfies Record<string, string>

type TranslationKey = keyof typeof english
type Translation = Partial<Record<TranslationKey, string>>

const translated: Partial<Record<Exclude<LanguageCode, 'en'>, Translation>> = {
  fr: { 'nav.home': 'Accueil', 'nav.signIn': 'Se connecter', 'nav.createAccount': 'Créer un compte', 'nav.dashboard': 'Tableau de bord', 'nav.connectWallet': 'Connecter un portefeuille', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Feuille de route', 'nav.transactions': 'Transactions', 'nav.myNodes': 'Mes nœuds', 'nav.profile': 'Profil', 'nav.settings': 'Paramètres', 'nav.logout': 'Se déconnecter', 'nav.workspace': 'Espace de travail', 'common.loading': 'Chargement...', 'common.save': 'Enregistrer', 'common.saving': 'Enregistrement...', 'common.cancel': 'Annuler', 'common.copy': 'Copier', 'common.copied': 'Copié', 'common.fullName': 'Nom complet', 'common.emailAddress': 'Adresse e-mail', 'common.password': 'Mot de passe', 'common.confirmPassword': 'Confirmer le mot de passe', 'profile.accountOverview': 'Aperçu du compte', 'profile.personalInformation': 'Informations personnelles', 'profile.currentEmail': 'E-mail actuel', 'profile.verified': 'Vérifié', 'profile.notVerified': 'Non vérifié', 'profile.changeEmail': 'Modifier l’adresse e-mail', 'profile.newEmail': 'Nouvelle adresse e-mail', 'profile.currentPassword': 'Mot de passe actuel', 'profile.sendConfirmation': 'Envoyer la confirmation', 'profile.addPhoto': 'Ajouter une photo', 'profile.changePhoto': 'Changer la photo', 'profile.removePhoto': 'Supprimer la photo', 'profile.referralId': 'Identifiant de parrainage', 'settings.appearance': 'Apparence', 'settings.sound': 'Son', 'settings.soundEffects': 'Effets sonores', 'settings.volume': 'Volume', 'settings.notifications': 'Notifications', 'settings.security': 'Sécurité', 'settings.twoFactor': 'Authentification à deux facteurs', 'settings.enableTwoFactor': 'Activer l’authentification à deux facteurs', 'settings.disableTwoFactor': 'Désactiver l’authentification à deux facteurs', 'settings.recoveryCodes': 'Codes de récupération', 'settings.language': 'Langue', 'settings.currency': 'Devise', 'settings.dark': 'Sombre', 'settings.light': 'Clair', 'settings.system': 'Système' },
  es: { 'nav.home': 'Inicio', 'nav.signIn': 'Iniciar sesión', 'nav.createAccount': 'Crear cuenta', 'nav.dashboard': 'Panel', 'nav.connectWallet': 'Conectar cartera', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Hoja de ruta', 'nav.transactions': 'Transacciones', 'nav.myNodes': 'Mis nodos', 'nav.profile': 'Perfil', 'nav.settings': 'Configuración', 'nav.logout': 'Cerrar sesión', 'nav.workspace': 'Espacio de trabajo', 'common.loading': 'Cargando...', 'common.save': 'Guardar', 'common.saving': 'Guardando...', 'common.cancel': 'Cancelar', 'common.copy': 'Copiar', 'common.copied': 'Copiado', 'common.fullName': 'Nombre completo', 'common.emailAddress': 'Correo electrónico', 'common.password': 'Contraseña', 'common.confirmPassword': 'Confirmar contraseña', 'profile.accountOverview': 'Resumen de la cuenta', 'profile.personalInformation': 'Información personal', 'profile.currentEmail': 'Correo actual', 'profile.verified': 'Verificado', 'profile.notVerified': 'Sin verificar', 'profile.changeEmail': 'Cambiar correo electrónico', 'profile.newEmail': 'Nuevo correo electrónico', 'profile.currentPassword': 'Contraseña actual', 'profile.sendConfirmation': 'Enviar confirmación', 'profile.addPhoto': 'Añadir foto', 'profile.changePhoto': 'Cambiar foto', 'profile.removePhoto': 'Eliminar foto', 'profile.referralId': 'ID de referido', 'settings.appearance': 'Apariencia', 'settings.sound': 'Sonido', 'settings.soundEffects': 'Efectos de sonido', 'settings.volume': 'Volumen', 'settings.notifications': 'Notificaciones', 'settings.security': 'Seguridad', 'settings.twoFactor': 'Autenticación de dos factores', 'settings.enableTwoFactor': 'Activar autenticación de dos factores', 'settings.disableTwoFactor': 'Desactivar autenticación de dos factores', 'settings.recoveryCodes': 'Códigos de recuperación', 'settings.language': 'Idioma', 'settings.currency': 'Moneda', 'settings.dark': 'Oscuro', 'settings.light': 'Claro', 'settings.system': 'Sistema' },
  pt: { 'nav.home': 'Início', 'nav.signIn': 'Entrar', 'nav.createAccount': 'Criar conta', 'nav.dashboard': 'Painel', 'nav.connectWallet': 'Conectar carteira', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Roteiro', 'nav.transactions': 'Transações', 'nav.myNodes': 'Meus nós', 'nav.profile': 'Perfil', 'nav.settings': 'Configurações', 'nav.logout': 'Sair', 'nav.workspace': 'Área de trabalho', 'common.loading': 'Carregando...', 'common.save': 'Salvar', 'common.saving': 'Salvando...', 'common.cancel': 'Cancelar', 'common.copy': 'Copiar', 'common.copied': 'Copiado', 'common.fullName': 'Nome completo', 'common.emailAddress': 'Endereço de e-mail', 'common.password': 'Senha', 'common.confirmPassword': 'Confirmar senha', 'profile.accountOverview': 'Visão geral da conta', 'profile.personalInformation': 'Informações pessoais', 'profile.currentEmail': 'E-mail atual', 'profile.verified': 'Verificado', 'profile.notVerified': 'Não verificado', 'profile.changeEmail': 'Alterar e-mail', 'profile.newEmail': 'Novo endereço de e-mail', 'profile.currentPassword': 'Senha atual', 'profile.sendConfirmation': 'Enviar confirmação', 'profile.addPhoto': 'Adicionar foto', 'profile.changePhoto': 'Alterar foto', 'profile.removePhoto': 'Remover foto', 'profile.referralId': 'ID de indicação', 'settings.appearance': 'Aparência', 'settings.sound': 'Som', 'settings.soundEffects': 'Efeitos sonoros', 'settings.volume': 'Volume', 'settings.notifications': 'Notificações', 'settings.security': 'Segurança', 'settings.twoFactor': 'Autenticação de dois fatores', 'settings.enableTwoFactor': 'Ativar autenticação de dois fatores', 'settings.disableTwoFactor': 'Desativar autenticação de dois fatores', 'settings.recoveryCodes': 'Códigos de recuperação', 'settings.language': 'Idioma', 'settings.currency': 'Moeda', 'settings.dark': 'Escuro', 'settings.light': 'Claro', 'settings.system': 'Sistema' },
  de: { 'nav.home': 'Startseite', 'nav.signIn': 'Anmelden', 'nav.createAccount': 'Konto erstellen', 'nav.dashboard': 'Übersicht', 'nav.connectWallet': 'Wallet verbinden', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Roadmap', 'nav.transactions': 'Transaktionen', 'nav.myNodes': 'Meine Nodes', 'nav.profile': 'Profil', 'nav.settings': 'Einstellungen', 'nav.logout': 'Abmelden', 'nav.workspace': 'Arbeitsbereich', 'common.loading': 'Wird geladen...', 'common.save': 'Speichern', 'common.saving': 'Wird gespeichert...', 'common.cancel': 'Abbrechen', 'common.copy': 'Kopieren', 'common.copied': 'Kopiert', 'common.fullName': 'Vollständiger Name', 'common.emailAddress': 'E-Mail-Adresse', 'common.password': 'Passwort', 'common.confirmPassword': 'Passwort bestätigen', 'profile.accountOverview': 'Kontoübersicht', 'profile.personalInformation': 'Persönliche Angaben', 'profile.currentEmail': 'Aktuelle E-Mail', 'profile.verified': 'Bestätigt', 'profile.notVerified': 'Nicht bestätigt', 'profile.changeEmail': 'E-Mail-Adresse ändern', 'profile.newEmail': 'Neue E-Mail-Adresse', 'profile.currentPassword': 'Aktuelles Passwort', 'profile.sendConfirmation': 'Bestätigung senden', 'profile.addPhoto': 'Foto hinzufügen', 'profile.changePhoto': 'Foto ändern', 'profile.removePhoto': 'Foto entfernen', 'profile.referralId': 'Empfehlungs-ID', 'settings.appearance': 'Darstellung', 'settings.sound': 'Ton', 'settings.soundEffects': 'Soundeffekte', 'settings.volume': 'Lautstärke', 'settings.notifications': 'Benachrichtigungen', 'settings.security': 'Sicherheit', 'settings.twoFactor': 'Zwei-Faktor-Authentifizierung', 'settings.enableTwoFactor': 'Zwei-Faktor-Authentifizierung aktivieren', 'settings.disableTwoFactor': 'Zwei-Faktor-Authentifizierung deaktivieren', 'settings.recoveryCodes': 'Wiederherstellungscodes', 'settings.language': 'Sprache', 'settings.currency': 'Währung', 'settings.dark': 'Dunkel', 'settings.light': 'Hell', 'settings.system': 'System' },
  it: { 'nav.home': 'Home', 'nav.signIn': 'Accedi', 'nav.createAccount': 'Crea account', 'nav.dashboard': 'Pannello', 'nav.connectWallet': 'Connetti wallet', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Roadmap', 'nav.transactions': 'Transazioni', 'nav.myNodes': 'I miei nodi', 'nav.profile': 'Profilo', 'nav.settings': 'Impostazioni', 'nav.logout': 'Esci', 'nav.workspace': 'Area di lavoro', 'common.loading': 'Caricamento...', 'common.save': 'Salva', 'common.saving': 'Salvataggio...', 'common.cancel': 'Annulla', 'common.copy': 'Copia', 'common.copied': 'Copiato', 'common.fullName': 'Nome completo', 'common.emailAddress': 'Indirizzo e-mail', 'common.password': 'Password', 'common.confirmPassword': 'Conferma password', 'profile.accountOverview': 'Panoramica account', 'profile.personalInformation': 'Informazioni personali', 'profile.currentEmail': 'E-mail attuale', 'profile.verified': 'Verificato', 'profile.notVerified': 'Non verificato', 'profile.changeEmail': 'Modifica e-mail', 'profile.newEmail': 'Nuovo indirizzo e-mail', 'profile.currentPassword': 'Password attuale', 'profile.sendConfirmation': 'Invia conferma', 'profile.addPhoto': 'Aggiungi foto', 'profile.changePhoto': 'Cambia foto', 'profile.removePhoto': 'Rimuovi foto', 'profile.referralId': 'ID referral', 'settings.appearance': 'Aspetto', 'settings.sound': 'Audio', 'settings.soundEffects': 'Effetti sonori', 'settings.volume': 'Volume', 'settings.notifications': 'Notifiche', 'settings.security': 'Sicurezza', 'settings.twoFactor': 'Autenticazione a due fattori', 'settings.enableTwoFactor': 'Attiva autenticazione a due fattori', 'settings.disableTwoFactor': 'Disattiva autenticazione a due fattori', 'settings.recoveryCodes': 'Codici di recupero', 'settings.language': 'Lingua', 'settings.currency': 'Valuta', 'settings.dark': 'Scuro', 'settings.light': 'Chiaro', 'settings.system': 'Sistema' },
  nl: { 'nav.home': 'Start', 'nav.signIn': 'Inloggen', 'nav.createAccount': 'Account maken', 'nav.dashboard': 'Dashboard', 'nav.connectWallet': 'Wallet verbinden', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Roadmap', 'nav.transactions': 'Transacties', 'nav.myNodes': 'Mijn nodes', 'nav.profile': 'Profiel', 'nav.settings': 'Instellingen', 'nav.logout': 'Uitloggen', 'nav.workspace': 'Werkruimte', 'common.loading': 'Laden...', 'common.save': 'Opslaan', 'common.saving': 'Opslaan...', 'common.cancel': 'Annuleren', 'common.copy': 'Kopiëren', 'common.copied': 'Gekopieerd', 'common.fullName': 'Volledige naam', 'common.emailAddress': 'E-mailadres', 'common.password': 'Wachtwoord', 'common.confirmPassword': 'Wachtwoord bevestigen', 'profile.accountOverview': 'Accountoverzicht', 'profile.personalInformation': 'Persoonlijke gegevens', 'profile.currentEmail': 'Huidig e-mailadres', 'profile.verified': 'Geverifieerd', 'profile.notVerified': 'Niet geverifieerd', 'profile.changeEmail': 'E-mailadres wijzigen', 'profile.newEmail': 'Nieuw e-mailadres', 'profile.currentPassword': 'Huidig wachtwoord', 'profile.sendConfirmation': 'Bevestiging verzenden', 'profile.addPhoto': 'Foto toevoegen', 'profile.changePhoto': 'Foto wijzigen', 'profile.removePhoto': 'Foto verwijderen', 'profile.referralId': 'Verwijzings-ID', 'settings.appearance': 'Weergave', 'settings.sound': 'Geluid', 'settings.soundEffects': 'Geluidseffecten', 'settings.volume': 'Volume', 'settings.notifications': 'Meldingen', 'settings.security': 'Beveiliging', 'settings.twoFactor': 'Tweestapsverificatie', 'settings.enableTwoFactor': 'Tweestapsverificatie inschakelen', 'settings.disableTwoFactor': 'Tweestapsverificatie uitschakelen', 'settings.recoveryCodes': 'Herstelcodes', 'settings.language': 'Taal', 'settings.currency': 'Valuta', 'settings.dark': 'Donker', 'settings.light': 'Licht', 'settings.system': 'Systeem' },
  ru: { 'nav.home': 'Главная', 'nav.signIn': 'Войти', 'nav.createAccount': 'Создать аккаунт', 'nav.dashboard': 'Панель', 'nav.connectWallet': 'Подключить кошелёк', 'nav.staking': 'Стейкинг', 'nav.tokenomics': 'Токеномика', 'nav.roadmap': 'Дорожная карта', 'nav.transactions': 'Транзакции', 'nav.myNodes': 'Мои узлы', 'nav.profile': 'Профиль', 'nav.settings': 'Настройки', 'nav.logout': 'Выйти', 'nav.workspace': 'Рабочая область', 'common.loading': 'Загрузка...', 'common.save': 'Сохранить', 'common.saving': 'Сохранение...', 'common.cancel': 'Отмена', 'common.copy': 'Копировать', 'common.copied': 'Скопировано', 'common.fullName': 'Полное имя', 'common.emailAddress': 'Адрес эл. почты', 'common.password': 'Пароль', 'common.confirmPassword': 'Подтвердите пароль', 'profile.accountOverview': 'Обзор аккаунта', 'profile.personalInformation': 'Личные данные', 'profile.currentEmail': 'Текущая почта', 'profile.verified': 'Подтверждено', 'profile.notVerified': 'Не подтверждено', 'profile.changeEmail': 'Изменить адрес почты', 'profile.newEmail': 'Новый адрес почты', 'profile.currentPassword': 'Текущий пароль', 'profile.sendConfirmation': 'Отправить подтверждение', 'profile.addPhoto': 'Добавить фото', 'profile.changePhoto': 'Изменить фото', 'profile.removePhoto': 'Удалить фото', 'profile.referralId': 'Реферальный ID', 'settings.appearance': 'Внешний вид', 'settings.sound': 'Звук', 'settings.soundEffects': 'Звуковые эффекты', 'settings.volume': 'Громкость', 'settings.notifications': 'Уведомления', 'settings.security': 'Безопасность', 'settings.twoFactor': 'Двухфакторная аутентификация', 'settings.enableTwoFactor': 'Включить двухфакторную аутентификацию', 'settings.disableTwoFactor': 'Отключить двухфакторную аутентификацию', 'settings.recoveryCodes': 'Коды восстановления', 'settings.language': 'Язык', 'settings.currency': 'Валюта', 'settings.dark': 'Тёмная', 'settings.light': 'Светлая', 'settings.system': 'Системная' },
  uk: { 'nav.home': 'Головна', 'nav.signIn': 'Увійти', 'nav.createAccount': 'Створити обліковий запис', 'nav.dashboard': 'Панель', 'nav.connectWallet': 'Під’єднати гаманець', 'nav.staking': 'Стейкінг', 'nav.tokenomics': 'Токеноміка', 'nav.roadmap': 'Дорожня карта', 'nav.transactions': 'Транзакції', 'nav.myNodes': 'Мої вузли', 'nav.profile': 'Профіль', 'nav.settings': 'Налаштування', 'nav.logout': 'Вийти', 'nav.workspace': 'Робочий простір', 'common.loading': 'Завантаження...', 'common.save': 'Зберегти', 'common.saving': 'Збереження...', 'common.cancel': 'Скасувати', 'common.copy': 'Копіювати', 'common.copied': 'Скопійовано', 'common.fullName': 'Повне ім’я', 'common.emailAddress': 'Електронна адреса', 'common.password': 'Пароль', 'common.confirmPassword': 'Підтвердьте пароль', 'profile.accountOverview': 'Огляд облікового запису', 'profile.personalInformation': 'Особисті дані', 'profile.currentEmail': 'Поточна адреса', 'profile.verified': 'Підтверджено', 'profile.notVerified': 'Не підтверджено', 'profile.changeEmail': 'Змінити адресу', 'profile.newEmail': 'Нова адреса', 'profile.currentPassword': 'Поточний пароль', 'profile.sendConfirmation': 'Надіслати підтвердження', 'profile.addPhoto': 'Додати фото', 'profile.changePhoto': 'Змінити фото', 'profile.removePhoto': 'Видалити фото', 'profile.referralId': 'Реферальний ID', 'settings.appearance': 'Вигляд', 'settings.sound': 'Звук', 'settings.soundEffects': 'Звукові ефекти', 'settings.volume': 'Гучність', 'settings.notifications': 'Сповіщення', 'settings.security': 'Безпека', 'settings.twoFactor': 'Двофакторна автентифікація', 'settings.enableTwoFactor': 'Увімкнути двофакторну автентифікацію', 'settings.disableTwoFactor': 'Вимкнути двофакторну автентифікацію', 'settings.recoveryCodes': 'Коди відновлення', 'settings.language': 'Мова', 'settings.currency': 'Валюта', 'settings.dark': 'Темна', 'settings.light': 'Світла', 'settings.system': 'Системна' },
  pl: { 'nav.home': 'Strona główna', 'nav.signIn': 'Zaloguj się', 'nav.createAccount': 'Utwórz konto', 'nav.dashboard': 'Panel', 'nav.connectWallet': 'Połącz portfel', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomika', 'nav.roadmap': 'Mapa drogowa', 'nav.transactions': 'Transakcje', 'nav.myNodes': 'Moje węzły', 'nav.profile': 'Profil', 'nav.settings': 'Ustawienia', 'nav.logout': 'Wyloguj się', 'nav.workspace': 'Obszar roboczy', 'common.loading': 'Ładowanie...', 'common.save': 'Zapisz', 'common.saving': 'Zapisywanie...', 'common.cancel': 'Anuluj', 'common.copy': 'Kopiuj', 'common.copied': 'Skopiowano', 'common.fullName': 'Imię i nazwisko', 'common.emailAddress': 'Adres e-mail', 'common.password': 'Hasło', 'common.confirmPassword': 'Potwierdź hasło', 'profile.accountOverview': 'Przegląd konta', 'profile.personalInformation': 'Dane osobowe', 'profile.currentEmail': 'Obecny e-mail', 'profile.verified': 'Zweryfikowany', 'profile.notVerified': 'Niezweryfikowany', 'profile.changeEmail': 'Zmień adres e-mail', 'profile.newEmail': 'Nowy adres e-mail', 'profile.currentPassword': 'Obecne hasło', 'profile.sendConfirmation': 'Wyślij potwierdzenie', 'profile.addPhoto': 'Dodaj zdjęcie', 'profile.changePhoto': 'Zmień zdjęcie', 'profile.removePhoto': 'Usuń zdjęcie', 'profile.referralId': 'ID polecenia', 'settings.appearance': 'Wygląd', 'settings.sound': 'Dźwięk', 'settings.soundEffects': 'Efekty dźwiękowe', 'settings.volume': 'Głośność', 'settings.notifications': 'Powiadomienia', 'settings.security': 'Bezpieczeństwo', 'settings.twoFactor': 'Uwierzytelnianie dwuskładnikowe', 'settings.enableTwoFactor': 'Włącz uwierzytelnianie dwuskładnikowe', 'settings.disableTwoFactor': 'Wyłącz uwierzytelnianie dwuskładnikowe', 'settings.recoveryCodes': 'Kody odzyskiwania', 'settings.language': 'Język', 'settings.currency': 'Waluta', 'settings.dark': 'Ciemny', 'settings.light': 'Jasny', 'settings.system': 'Systemowy' },
  tr: { 'nav.home': 'Ana sayfa', 'nav.signIn': 'Giriş yap', 'nav.createAccount': 'Hesap oluştur', 'nav.dashboard': 'Panel', 'nav.connectWallet': 'Cüzdanı bağla', 'nav.staking': 'Staking', 'nav.tokenomics': 'Token ekonomisi', 'nav.roadmap': 'Yol haritası', 'nav.transactions': 'İşlemler', 'nav.myNodes': 'Düğümlerim', 'nav.profile': 'Profil', 'nav.settings': 'Ayarlar', 'nav.logout': 'Çıkış yap', 'nav.workspace': 'Çalışma alanı', 'common.loading': 'Yükleniyor...', 'common.save': 'Kaydet', 'common.saving': 'Kaydediliyor...', 'common.cancel': 'İptal', 'common.copy': 'Kopyala', 'common.copied': 'Kopyalandı', 'common.fullName': 'Ad soyad', 'common.emailAddress': 'E-posta adresi', 'common.password': 'Parola', 'common.confirmPassword': 'Parolayı onayla', 'profile.accountOverview': 'Hesap özeti', 'profile.personalInformation': 'Kişisel bilgiler', 'profile.currentEmail': 'Mevcut e-posta', 'profile.verified': 'Doğrulandı', 'profile.notVerified': 'Doğrulanmadı', 'profile.changeEmail': 'E-posta adresini değiştir', 'profile.newEmail': 'Yeni e-posta adresi', 'profile.currentPassword': 'Mevcut parola', 'profile.sendConfirmation': 'Onay gönder', 'profile.addPhoto': 'Fotoğraf ekle', 'profile.changePhoto': 'Fotoğrafı değiştir', 'profile.removePhoto': 'Fotoğrafı kaldır', 'profile.referralId': 'Davet kimliği', 'settings.appearance': 'Görünüm', 'settings.sound': 'Ses', 'settings.soundEffects': 'Ses efektleri', 'settings.volume': 'Ses düzeyi', 'settings.notifications': 'Bildirimler', 'settings.security': 'Güvenlik', 'settings.twoFactor': 'İki faktörlü kimlik doğrulama', 'settings.enableTwoFactor': 'İki faktörlü kimlik doğrulamayı etkinleştir', 'settings.disableTwoFactor': 'İki faktörlü kimlik doğrulamayı devre dışı bırak', 'settings.recoveryCodes': 'Kurtarma kodları', 'settings.language': 'Dil', 'settings.currency': 'Para birimi', 'settings.dark': 'Koyu', 'settings.light': 'Açık', 'settings.system': 'Sistem' },
  ar: { 'nav.home': 'الرئيسية', 'nav.signIn': 'تسجيل الدخول', 'nav.createAccount': 'إنشاء حساب', 'nav.dashboard': 'لوحة التحكم', 'nav.connectWallet': 'ربط المحفظة', 'nav.staking': 'التخزين', 'nav.tokenomics': 'اقتصاديات الرموز', 'nav.roadmap': 'خارطة الطريق', 'nav.transactions': 'المعاملات', 'nav.myNodes': 'عُقدي', 'nav.profile': 'الملف الشخصي', 'nav.settings': 'الإعدادات', 'nav.logout': 'تسجيل الخروج', 'nav.workspace': 'مساحة العمل', 'common.loading': 'جارٍ التحميل...', 'common.save': 'حفظ', 'common.saving': 'جارٍ الحفظ...', 'common.cancel': 'إلغاء', 'common.copy': 'نسخ', 'common.copied': 'تم النسخ', 'common.fullName': 'الاسم الكامل', 'common.emailAddress': 'عنوان البريد الإلكتروني', 'common.password': 'كلمة المرور', 'common.confirmPassword': 'تأكيد كلمة المرور', 'profile.accountOverview': 'نظرة عامة على الحساب', 'profile.personalInformation': 'المعلومات الشخصية', 'profile.currentEmail': 'البريد الحالي', 'profile.verified': 'تم التحقق', 'profile.notVerified': 'لم يتم التحقق', 'profile.changeEmail': 'تغيير البريد الإلكتروني', 'profile.newEmail': 'عنوان البريد الجديد', 'profile.currentPassword': 'كلمة المرور الحالية', 'profile.sendConfirmation': 'إرسال التأكيد', 'profile.addPhoto': 'إضافة صورة', 'profile.changePhoto': 'تغيير الصورة', 'profile.removePhoto': 'إزالة الصورة', 'profile.referralId': 'معرّف الإحالة', 'settings.appearance': 'المظهر', 'settings.sound': 'الصوت', 'settings.soundEffects': 'المؤثرات الصوتية', 'settings.volume': 'مستوى الصوت', 'settings.notifications': 'الإشعارات', 'settings.security': 'الأمان', 'settings.twoFactor': 'المصادقة الثنائية', 'settings.enableTwoFactor': 'تفعيل المصادقة الثنائية', 'settings.disableTwoFactor': 'تعطيل المصادقة الثنائية', 'settings.recoveryCodes': 'رموز الاسترداد', 'settings.language': 'اللغة', 'settings.currency': 'العملة', 'settings.dark': 'داكن', 'settings.light': 'فاتح', 'settings.system': 'النظام' },
  'zh-CN': { 'nav.home': '首页', 'nav.signIn': '登录', 'nav.createAccount': '创建账户', 'nav.dashboard': '控制面板', 'nav.connectWallet': '连接钱包', 'nav.staking': '质押', 'nav.tokenomics': '代币经济学', 'nav.roadmap': '路线图', 'nav.transactions': '交易记录', 'nav.myNodes': '我的节点', 'nav.profile': '个人资料', 'nav.settings': '设置', 'nav.logout': '退出登录', 'nav.workspace': '工作区', 'common.loading': '正在加载…', 'common.save': '保存', 'common.saving': '正在保存…', 'common.cancel': '取消', 'common.copy': '复制', 'common.copied': '已复制', 'common.fullName': '姓名', 'common.emailAddress': '电子邮箱', 'common.password': '密码', 'common.confirmPassword': '确认密码', 'profile.accountOverview': '账户概览', 'profile.personalInformation': '个人信息', 'profile.currentEmail': '当前邮箱', 'profile.verified': '已验证', 'profile.notVerified': '未验证', 'profile.changeEmail': '更改邮箱', 'profile.newEmail': '新邮箱地址', 'profile.currentPassword': '当前密码', 'profile.sendConfirmation': '发送确认邮件', 'profile.addPhoto': '添加照片', 'profile.changePhoto': '更换照片', 'profile.removePhoto': '移除照片', 'profile.referralId': '推荐 ID', 'settings.appearance': '外观', 'settings.sound': '声音', 'settings.soundEffects': '音效', 'settings.volume': '音量', 'settings.notifications': '通知', 'settings.security': '安全', 'settings.twoFactor': '双重身份验证', 'settings.enableTwoFactor': '启用双重身份验证', 'settings.disableTwoFactor': '停用双重身份验证', 'settings.recoveryCodes': '恢复代码', 'settings.language': '语言', 'settings.currency': '货币', 'settings.dark': '深色', 'settings.light': '浅色', 'settings.system': '跟随系统' },
  'zh-TW': { 'nav.home': '首頁', 'nav.signIn': '登入', 'nav.createAccount': '建立帳戶', 'nav.dashboard': '控制台', 'nav.connectWallet': '連接錢包', 'nav.staking': '質押', 'nav.tokenomics': '代幣經濟學', 'nav.roadmap': '路線圖', 'nav.transactions': '交易紀錄', 'nav.myNodes': '我的節點', 'nav.profile': '個人資料', 'nav.settings': '設定', 'nav.logout': '登出', 'nav.workspace': '工作區', 'common.loading': '載入中…', 'common.save': '儲存', 'common.saving': '儲存中…', 'common.cancel': '取消', 'common.copy': '複製', 'common.copied': '已複製', 'common.fullName': '姓名', 'common.emailAddress': '電子郵件地址', 'common.password': '密碼', 'common.confirmPassword': '確認密碼', 'profile.accountOverview': '帳戶總覽', 'profile.personalInformation': '個人資訊', 'profile.currentEmail': '目前電子郵件', 'profile.verified': '已驗證', 'profile.notVerified': '尚未驗證', 'profile.changeEmail': '變更電子郵件', 'profile.newEmail': '新的電子郵件地址', 'profile.currentPassword': '目前密碼', 'profile.sendConfirmation': '傳送確認信', 'profile.addPhoto': '新增照片', 'profile.changePhoto': '變更照片', 'profile.removePhoto': '移除照片', 'profile.referralId': '推薦 ID', 'settings.appearance': '外觀', 'settings.sound': '音效', 'settings.soundEffects': '介面音效', 'settings.volume': '音量', 'settings.notifications': '通知', 'settings.security': '安全性', 'settings.twoFactor': '雙因素驗證', 'settings.enableTwoFactor': '啟用雙因素驗證', 'settings.disableTwoFactor': '停用雙因素驗證', 'settings.recoveryCodes': '復原碼', 'settings.language': '語言', 'settings.currency': '貨幣', 'settings.dark': '深色', 'settings.light': '淺色', 'settings.system': '系統' },
  ja: { 'nav.home': 'ホーム', 'nav.signIn': 'ログイン', 'nav.createAccount': 'アカウントを作成', 'nav.dashboard': 'ダッシュボード', 'nav.connectWallet': 'ウォレットを接続', 'nav.staking': 'ステーキング', 'nav.tokenomics': 'トークノミクス', 'nav.roadmap': 'ロードマップ', 'nav.transactions': '取引履歴', 'nav.myNodes': 'マイノード', 'nav.profile': 'プロフィール', 'nav.settings': '設定', 'nav.logout': 'ログアウト', 'nav.workspace': 'ワークスペース', 'common.loading': '読み込み中…', 'common.save': '保存', 'common.saving': '保存中…', 'common.cancel': 'キャンセル', 'common.copy': 'コピー', 'common.copied': 'コピーしました', 'common.fullName': '氏名', 'common.emailAddress': 'メールアドレス', 'common.password': 'パスワード', 'common.confirmPassword': 'パスワードを確認', 'profile.accountOverview': 'アカウント概要', 'profile.personalInformation': '個人情報', 'profile.currentEmail': '現在のメールアドレス', 'profile.verified': '確認済み', 'profile.notVerified': '未確認', 'profile.changeEmail': 'メールアドレスを変更', 'profile.newEmail': '新しいメールアドレス', 'profile.currentPassword': '現在のパスワード', 'profile.sendConfirmation': '確認メールを送信', 'profile.addPhoto': '写真を追加', 'profile.changePhoto': '写真を変更', 'profile.removePhoto': '写真を削除', 'profile.referralId': '紹介 ID', 'settings.appearance': '外観', 'settings.sound': 'サウンド', 'settings.soundEffects': '効果音', 'settings.volume': '音量', 'settings.notifications': '通知', 'settings.security': 'セキュリティ', 'settings.twoFactor': '二要素認証', 'settings.enableTwoFactor': '二要素認証を有効にする', 'settings.disableTwoFactor': '二要素認証を無効にする', 'settings.recoveryCodes': 'リカバリーコード', 'settings.language': '言語', 'settings.currency': '通貨', 'settings.dark': 'ダーク', 'settings.light': 'ライト', 'settings.system': 'システム' },
  ko: { 'nav.home': '홈', 'nav.signIn': '로그인', 'nav.createAccount': '계정 만들기', 'nav.dashboard': '대시보드', 'nav.connectWallet': '지갑 연결', 'nav.staking': '스테이킹', 'nav.tokenomics': '토크노믹스', 'nav.roadmap': '로드맵', 'nav.transactions': '거래 내역', 'nav.myNodes': '내 노드', 'nav.profile': '프로필', 'nav.settings': '설정', 'nav.logout': '로그아웃', 'nav.workspace': '작업 공간', 'common.loading': '불러오는 중…', 'common.save': '저장', 'common.saving': '저장 중…', 'common.cancel': '취소', 'common.copy': '복사', 'common.copied': '복사됨', 'common.fullName': '이름', 'common.emailAddress': '이메일 주소', 'common.password': '비밀번호', 'common.confirmPassword': '비밀번호 확인', 'profile.accountOverview': '계정 개요', 'profile.personalInformation': '개인 정보', 'profile.currentEmail': '현재 이메일', 'profile.verified': '인증됨', 'profile.notVerified': '인증되지 않음', 'profile.changeEmail': '이메일 주소 변경', 'profile.newEmail': '새 이메일 주소', 'profile.currentPassword': '현재 비밀번호', 'profile.sendConfirmation': '확인 메일 보내기', 'profile.addPhoto': '사진 추가', 'profile.changePhoto': '사진 변경', 'profile.removePhoto': '사진 삭제', 'profile.referralId': '추천 ID', 'settings.appearance': '화면 설정', 'settings.sound': '사운드', 'settings.soundEffects': '효과음', 'settings.volume': '볼륨', 'settings.notifications': '알림', 'settings.security': '보안', 'settings.twoFactor': '2단계 인증', 'settings.enableTwoFactor': '2단계 인증 사용', 'settings.disableTwoFactor': '2단계 인증 사용 중지', 'settings.recoveryCodes': '복구 코드', 'settings.language': '언어', 'settings.currency': '통화', 'settings.dark': '어둡게', 'settings.light': '밝게', 'settings.system': '시스템 설정' },
  hi: { 'nav.home': 'मुखपृष्ठ', 'nav.signIn': 'साइन इन', 'nav.createAccount': 'खाता बनाएँ', 'nav.dashboard': 'डैशबोर्ड', 'nav.connectWallet': 'वॉलेट कनेक्ट करें', 'nav.staking': 'स्टेकिंग', 'nav.tokenomics': 'टोकनोमिक्स', 'nav.roadmap': 'रोडमैप', 'nav.transactions': 'लेन-देन', 'nav.myNodes': 'मेरे नोड', 'nav.profile': 'प्रोफ़ाइल', 'nav.settings': 'सेटिंग', 'nav.logout': 'साइन आउट', 'nav.workspace': 'कार्यस्थल', 'common.loading': 'लोड हो रहा है...', 'common.save': 'सहेजें', 'common.saving': 'सहेजा जा रहा है...', 'common.cancel': 'रद्द करें', 'common.copy': 'कॉपी करें', 'common.copied': 'कॉपी हो गया', 'common.fullName': 'पूरा नाम', 'common.emailAddress': 'ईमेल पता', 'common.password': 'पासवर्ड', 'common.confirmPassword': 'पासवर्ड की पुष्टि करें', 'profile.accountOverview': 'खाते का सारांश', 'profile.personalInformation': 'व्यक्तिगत जानकारी', 'profile.currentEmail': 'वर्तमान ईमेल', 'profile.verified': 'सत्यापित', 'profile.notVerified': 'सत्यापित नहीं', 'profile.changeEmail': 'ईमेल पता बदलें', 'profile.newEmail': 'नया ईमेल पता', 'profile.currentPassword': 'वर्तमान पासवर्ड', 'profile.sendConfirmation': 'पुष्टिकरण भेजें', 'profile.addPhoto': 'फ़ोटो जोड़ें', 'profile.changePhoto': 'फ़ोटो बदलें', 'profile.removePhoto': 'फ़ोटो हटाएँ', 'profile.referralId': 'रेफ़रल आईडी', 'settings.appearance': 'दिखावट', 'settings.sound': 'ध्वनि', 'settings.soundEffects': 'ध्वनि प्रभाव', 'settings.volume': 'आवाज़', 'settings.notifications': 'सूचनाएँ', 'settings.security': 'सुरक्षा', 'settings.twoFactor': 'दो-कारक प्रमाणीकरण', 'settings.enableTwoFactor': 'दो-कारक प्रमाणीकरण चालू करें', 'settings.disableTwoFactor': 'दो-कारक प्रमाणीकरण बंद करें', 'settings.recoveryCodes': 'पुनर्प्राप्ति कोड', 'settings.language': 'भाषा', 'settings.currency': 'मुद्रा', 'settings.dark': 'गहरा', 'settings.light': 'हल्का', 'settings.system': 'सिस्टम' },
  id: { 'nav.home': 'Beranda', 'nav.signIn': 'Masuk', 'nav.createAccount': 'Buat akun', 'nav.dashboard': 'Dasbor', 'nav.connectWallet': 'Hubungkan dompet', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Peta jalan', 'nav.transactions': 'Transaksi', 'nav.myNodes': 'Node saya', 'nav.profile': 'Profil', 'nav.settings': 'Pengaturan', 'nav.logout': 'Keluar', 'nav.workspace': 'Ruang kerja', 'common.loading': 'Memuat...', 'common.save': 'Simpan', 'common.saving': 'Menyimpan...', 'common.cancel': 'Batal', 'common.copy': 'Salin', 'common.copied': 'Tersalin', 'common.fullName': 'Nama lengkap', 'common.emailAddress': 'Alamat email', 'common.password': 'Kata sandi', 'common.confirmPassword': 'Konfirmasi kata sandi', 'profile.accountOverview': 'Ringkasan akun', 'profile.personalInformation': 'Informasi pribadi', 'profile.currentEmail': 'Email saat ini', 'profile.verified': 'Terverifikasi', 'profile.notVerified': 'Belum terverifikasi', 'profile.changeEmail': 'Ubah alamat email', 'profile.newEmail': 'Alamat email baru', 'profile.currentPassword': 'Kata sandi saat ini', 'profile.sendConfirmation': 'Kirim konfirmasi', 'profile.addPhoto': 'Tambah foto', 'profile.changePhoto': 'Ganti foto', 'profile.removePhoto': 'Hapus foto', 'profile.referralId': 'ID referral', 'settings.appearance': 'Tampilan', 'settings.sound': 'Suara', 'settings.soundEffects': 'Efek suara', 'settings.volume': 'Volume', 'settings.notifications': 'Notifikasi', 'settings.security': 'Keamanan', 'settings.twoFactor': 'Autentikasi dua faktor', 'settings.enableTwoFactor': 'Aktifkan autentikasi dua faktor', 'settings.disableTwoFactor': 'Nonaktifkan autentikasi dua faktor', 'settings.recoveryCodes': 'Kode pemulihan', 'settings.language': 'Bahasa', 'settings.currency': 'Mata uang', 'settings.dark': 'Gelap', 'settings.light': 'Terang', 'settings.system': 'Sistem' },
  vi: { 'nav.home': 'Trang chủ', 'nav.signIn': 'Đăng nhập', 'nav.createAccount': 'Tạo tài khoản', 'nav.dashboard': 'Bảng điều khiển', 'nav.connectWallet': 'Kết nối ví', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Lộ trình', 'nav.transactions': 'Giao dịch', 'nav.myNodes': 'Node của tôi', 'nav.profile': 'Hồ sơ', 'nav.settings': 'Cài đặt', 'nav.logout': 'Đăng xuất', 'nav.workspace': 'Không gian làm việc', 'common.loading': 'Đang tải...', 'common.save': 'Lưu', 'common.saving': 'Đang lưu...', 'common.cancel': 'Hủy', 'common.copy': 'Sao chép', 'common.copied': 'Đã sao chép', 'common.fullName': 'Họ và tên', 'common.emailAddress': 'Địa chỉ email', 'common.password': 'Mật khẩu', 'common.confirmPassword': 'Xác nhận mật khẩu', 'profile.accountOverview': 'Tổng quan tài khoản', 'profile.personalInformation': 'Thông tin cá nhân', 'profile.currentEmail': 'Email hiện tại', 'profile.verified': 'Đã xác minh', 'profile.notVerified': 'Chưa xác minh', 'profile.changeEmail': 'Đổi địa chỉ email', 'profile.newEmail': 'Địa chỉ email mới', 'profile.currentPassword': 'Mật khẩu hiện tại', 'profile.sendConfirmation': 'Gửi xác nhận', 'profile.addPhoto': 'Thêm ảnh', 'profile.changePhoto': 'Đổi ảnh', 'profile.removePhoto': 'Xóa ảnh', 'profile.referralId': 'ID giới thiệu', 'settings.appearance': 'Giao diện', 'settings.sound': 'Âm thanh', 'settings.soundEffects': 'Hiệu ứng âm thanh', 'settings.volume': 'Âm lượng', 'settings.notifications': 'Thông báo', 'settings.security': 'Bảo mật', 'settings.twoFactor': 'Xác thực hai yếu tố', 'settings.enableTwoFactor': 'Bật xác thực hai yếu tố', 'settings.disableTwoFactor': 'Tắt xác thực hai yếu tố', 'settings.recoveryCodes': 'Mã khôi phục', 'settings.language': 'Ngôn ngữ', 'settings.currency': 'Tiền tệ', 'settings.dark': 'Tối', 'settings.light': 'Sáng', 'settings.system': 'Hệ thống' },
  th: { 'nav.home': 'หน้าหลัก', 'nav.signIn': 'เข้าสู่ระบบ', 'nav.createAccount': 'สร้างบัญชี', 'nav.dashboard': 'แดชบอร์ด', 'nav.connectWallet': 'เชื่อมต่อกระเป๋าเงิน', 'nav.staking': 'สเตกกิง', 'nav.tokenomics': 'โทเคโนมิกส์', 'nav.roadmap': 'แผนงาน', 'nav.transactions': 'ธุรกรรม', 'nav.myNodes': 'โหนดของฉัน', 'nav.profile': 'โปรไฟล์', 'nav.settings': 'การตั้งค่า', 'nav.logout': 'ออกจากระบบ', 'nav.workspace': 'พื้นที่ทำงาน', 'common.loading': 'กำลังโหลด...', 'common.save': 'บันทึก', 'common.saving': 'กำลังบันทึก...', 'common.cancel': 'ยกเลิก', 'common.copy': 'คัดลอก', 'common.copied': 'คัดลอกแล้ว', 'common.fullName': 'ชื่อ-นามสกุล', 'common.emailAddress': 'ที่อยู่อีเมล', 'common.password': 'รหัสผ่าน', 'common.confirmPassword': 'ยืนยันรหัสผ่าน', 'profile.accountOverview': 'ภาพรวมบัญชี', 'profile.personalInformation': 'ข้อมูลส่วนตัว', 'profile.currentEmail': 'อีเมลปัจจุบัน', 'profile.verified': 'ยืนยันแล้ว', 'profile.notVerified': 'ยังไม่ยืนยัน', 'profile.changeEmail': 'เปลี่ยนที่อยู่อีเมล', 'profile.newEmail': 'ที่อยู่อีเมลใหม่', 'profile.currentPassword': 'รหัสผ่านปัจจุบัน', 'profile.sendConfirmation': 'ส่งการยืนยัน', 'profile.addPhoto': 'เพิ่มรูปภาพ', 'profile.changePhoto': 'เปลี่ยนรูปภาพ', 'profile.removePhoto': 'ลบรูปภาพ', 'profile.referralId': 'รหัสแนะนำ', 'settings.appearance': 'รูปลักษณ์', 'settings.sound': 'เสียง', 'settings.soundEffects': 'เอฟเฟกต์เสียง', 'settings.volume': 'ระดับเสียง', 'settings.notifications': 'การแจ้งเตือน', 'settings.security': 'ความปลอดภัย', 'settings.twoFactor': 'การยืนยันตัวตนสองขั้นตอน', 'settings.enableTwoFactor': 'เปิดใช้การยืนยันตัวตนสองขั้นตอน', 'settings.disableTwoFactor': 'ปิดการยืนยันตัวตนสองขั้นตอน', 'settings.recoveryCodes': 'รหัสกู้คืน', 'settings.language': 'ภาษา', 'settings.currency': 'สกุลเงิน', 'settings.dark': 'มืด', 'settings.light': 'สว่าง', 'settings.system': 'ตามระบบ' },
  bn: { 'nav.home': 'হোম', 'nav.signIn': 'সাইন ইন', 'nav.createAccount': 'অ্যাকাউন্ট তৈরি করুন', 'nav.dashboard': 'ড্যাশবোর্ড', 'nav.connectWallet': 'ওয়ালেট সংযুক্ত করুন', 'nav.staking': 'স্টেকিং', 'nav.tokenomics': 'টোকেনমিক্স', 'nav.roadmap': 'রোডম্যাপ', 'nav.transactions': 'লেনদেন', 'nav.myNodes': 'আমার নোড', 'nav.profile': 'প্রোফাইল', 'nav.settings': 'সেটিংস', 'nav.logout': 'সাইন আউট', 'nav.workspace': 'কর্মক্ষেত্র', 'common.loading': 'লোড হচ্ছে...', 'common.save': 'সংরক্ষণ', 'common.saving': 'সংরক্ষণ হচ্ছে...', 'common.cancel': 'বাতিল', 'common.copy': 'কপি', 'common.copied': 'কপি হয়েছে', 'common.fullName': 'পূর্ণ নাম', 'common.emailAddress': 'ইমেল ঠিকানা', 'common.password': 'পাসওয়ার্ড', 'common.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন', 'profile.accountOverview': 'অ্যাকাউন্টের সারাংশ', 'profile.personalInformation': 'ব্যক্তিগত তথ্য', 'profile.currentEmail': 'বর্তমান ইমেল', 'profile.verified': 'যাচাইকৃত', 'profile.notVerified': 'যাচাই হয়নি', 'profile.changeEmail': 'ইমেল ঠিকানা পরিবর্তন', 'profile.newEmail': 'নতুন ইমেল ঠিকানা', 'profile.currentPassword': 'বর্তমান পাসওয়ার্ড', 'profile.sendConfirmation': 'নিশ্চিতকরণ পাঠান', 'profile.addPhoto': 'ছবি যোগ করুন', 'profile.changePhoto': 'ছবি বদলান', 'profile.removePhoto': 'ছবি সরান', 'profile.referralId': 'রেফারেল আইডি', 'settings.appearance': 'চেহারা', 'settings.sound': 'শব্দ', 'settings.soundEffects': 'সাউন্ড ইফেক্ট', 'settings.volume': 'ভলিউম', 'settings.notifications': 'বিজ্ঞপ্তি', 'settings.security': 'নিরাপত্তা', 'settings.twoFactor': 'দুই-ধাপ যাচাইকরণ', 'settings.enableTwoFactor': 'দুই-ধাপ যাচাইকরণ চালু করুন', 'settings.disableTwoFactor': 'দুই-ধাপ যাচাইকরণ বন্ধ করুন', 'settings.recoveryCodes': 'পুনরুদ্ধার কোড', 'settings.language': 'ভাষা', 'settings.currency': 'মুদ্রা', 'settings.dark': 'গাঢ়', 'settings.light': 'হালকা', 'settings.system': 'সিস্টেম' },
  ro: { 'nav.home': 'Acasă', 'nav.signIn': 'Autentificare', 'nav.createAccount': 'Creează cont', 'nav.dashboard': 'Panou', 'nav.connectWallet': 'Conectează portofelul', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Foaie de parcurs', 'nav.transactions': 'Tranzacții', 'nav.myNodes': 'Nodurile mele', 'nav.profile': 'Profil', 'nav.settings': 'Setări', 'nav.logout': 'Deconectare', 'nav.workspace': 'Spațiu de lucru', 'common.loading': 'Se încarcă...', 'common.save': 'Salvează', 'common.saving': 'Se salvează...', 'common.cancel': 'Anulează', 'common.copy': 'Copiază', 'common.copied': 'Copiat', 'common.fullName': 'Nume complet', 'common.emailAddress': 'Adresă de e-mail', 'common.password': 'Parolă', 'common.confirmPassword': 'Confirmă parola', 'profile.accountOverview': 'Prezentarea contului', 'profile.personalInformation': 'Informații personale', 'profile.currentEmail': 'E-mail actual', 'profile.verified': 'Verificat', 'profile.notVerified': 'Neverificat', 'profile.changeEmail': 'Schimbă adresa de e-mail', 'profile.newEmail': 'Adresă nouă de e-mail', 'profile.currentPassword': 'Parola actuală', 'profile.sendConfirmation': 'Trimite confirmarea', 'profile.addPhoto': 'Adaugă fotografie', 'profile.changePhoto': 'Schimbă fotografia', 'profile.removePhoto': 'Elimină fotografia', 'profile.referralId': 'ID de recomandare', 'settings.appearance': 'Aspect', 'settings.sound': 'Sunet', 'settings.soundEffects': 'Efecte sonore', 'settings.volume': 'Volum', 'settings.notifications': 'Notificări', 'settings.security': 'Securitate', 'settings.twoFactor': 'Autentificare cu doi factori', 'settings.enableTwoFactor': 'Activează autentificarea cu doi factori', 'settings.disableTwoFactor': 'Dezactivează autentificarea cu doi factori', 'settings.recoveryCodes': 'Coduri de recuperare', 'settings.language': 'Limbă', 'settings.currency': 'Monedă', 'settings.dark': 'Întunecat', 'settings.light': 'Deschis', 'settings.system': 'Sistem' },
  el: { 'nav.home': 'Αρχική', 'nav.signIn': 'Σύνδεση', 'nav.createAccount': 'Δημιουργία λογαριασμού', 'nav.dashboard': 'Πίνακας ελέγχου', 'nav.connectWallet': 'Σύνδεση πορτοφολιού', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomics', 'nav.roadmap': 'Οδικός χάρτης', 'nav.transactions': 'Συναλλαγές', 'nav.myNodes': 'Οι κόμβοι μου', 'nav.profile': 'Προφίλ', 'nav.settings': 'Ρυθμίσεις', 'nav.logout': 'Αποσύνδεση', 'nav.workspace': 'Χώρος εργασίας', 'common.loading': 'Φόρτωση...', 'common.save': 'Αποθήκευση', 'common.saving': 'Αποθήκευση...', 'common.cancel': 'Ακύρωση', 'common.copy': 'Αντιγραφή', 'common.copied': 'Αντιγράφηκε', 'common.fullName': 'Ονοματεπώνυμο', 'common.emailAddress': 'Διεύθυνση email', 'common.password': 'Κωδικός πρόσβασης', 'common.confirmPassword': 'Επιβεβαίωση κωδικού', 'profile.accountOverview': 'Επισκόπηση λογαριασμού', 'profile.personalInformation': 'Προσωπικά στοιχεία', 'profile.currentEmail': 'Τρέχον email', 'profile.verified': 'Επαληθευμένο', 'profile.notVerified': 'Μη επαληθευμένο', 'profile.changeEmail': 'Αλλαγή διεύθυνσης email', 'profile.newEmail': 'Νέα διεύθυνση email', 'profile.currentPassword': 'Τρέχων κωδικός', 'profile.sendConfirmation': 'Αποστολή επιβεβαίωσης', 'profile.addPhoto': 'Προσθήκη φωτογραφίας', 'profile.changePhoto': 'Αλλαγή φωτογραφίας', 'profile.removePhoto': 'Αφαίρεση φωτογραφίας', 'profile.referralId': 'Κωδικός παραπομπής', 'settings.appearance': 'Εμφάνιση', 'settings.sound': 'Ήχος', 'settings.soundEffects': 'Ηχητικά εφέ', 'settings.volume': 'Ένταση', 'settings.notifications': 'Ειδοποιήσεις', 'settings.security': 'Ασφάλεια', 'settings.twoFactor': 'Έλεγχος ταυτότητας δύο παραγόντων', 'settings.enableTwoFactor': 'Ενεργοποίηση ελέγχου δύο παραγόντων', 'settings.disableTwoFactor': 'Απενεργοποίηση ελέγχου δύο παραγόντων', 'settings.recoveryCodes': 'Κωδικοί ανάκτησης', 'settings.language': 'Γλώσσα', 'settings.currency': 'Νόμισμα', 'settings.dark': 'Σκούρο', 'settings.light': 'Φωτεινό', 'settings.system': 'Σύστημα' },
  sk: { 'nav.home': 'Domov', 'nav.signIn': 'Prihlásiť sa', 'nav.createAccount': 'Vytvoriť účet', 'nav.dashboard': 'Prehľad', 'nav.connectWallet': 'Pripojiť peňaženku', 'nav.staking': 'Staking', 'nav.tokenomics': 'Tokenomika', 'nav.roadmap': 'Plán', 'nav.transactions': 'Transakcie', 'nav.myNodes': 'Moje uzly', 'nav.profile': 'Profil', 'nav.settings': 'Nastavenia', 'nav.logout': 'Odhlásiť sa', 'nav.workspace': 'Pracovný priestor', 'common.loading': 'Načítava sa...', 'common.save': 'Uložiť', 'common.saving': 'Ukladá sa...', 'common.cancel': 'Zrušiť', 'common.copy': 'Kopírovať', 'common.copied': 'Skopírované', 'common.fullName': 'Celé meno', 'common.emailAddress': 'E-mailová adresa', 'common.password': 'Heslo', 'common.confirmPassword': 'Potvrdiť heslo', 'profile.accountOverview': 'Prehľad účtu', 'profile.personalInformation': 'Osobné údaje', 'profile.currentEmail': 'Aktuálny e-mail', 'profile.verified': 'Overené', 'profile.notVerified': 'Neoverené', 'profile.changeEmail': 'Zmeniť e-mailovú adresu', 'profile.newEmail': 'Nová e-mailová adresa', 'profile.currentPassword': 'Aktuálne heslo', 'profile.sendConfirmation': 'Odoslať potvrdenie', 'profile.addPhoto': 'Pridať fotografiu', 'profile.changePhoto': 'Zmeniť fotografiu', 'profile.removePhoto': 'Odstrániť fotografiu', 'profile.referralId': 'Odporúčací identifikátor', 'settings.appearance': 'Vzhľad', 'settings.sound': 'Zvuk', 'settings.soundEffects': 'Zvukové efekty', 'settings.volume': 'Hlasitosť', 'settings.notifications': 'Upozornenia', 'settings.security': 'Zabezpečenie', 'settings.twoFactor': 'Dvojfaktorové overenie', 'settings.enableTwoFactor': 'Zapnúť dvojfaktorové overenie', 'settings.disableTwoFactor': 'Vypnúť dvojfaktorové overenie', 'settings.recoveryCodes': 'Obnovovacie kódy', 'settings.language': 'Jazyk', 'settings.currency': 'Mena', 'settings.dark': 'Tmavý', 'settings.light': 'Svetlý', 'settings.system': 'Systém' },
  zu: { 'nav.home': 'Ikhaya', 'nav.signIn': 'Ngena ngemvume', 'nav.createAccount': 'Dala i-akhawunti', 'nav.dashboard': 'Iphaneli', 'nav.connectWallet': 'Xhuma isikhwama', 'nav.staking': 'Ukubeka amathokheni', 'nav.tokenomics': 'Umnotho wamathokheni', 'nav.roadmap': 'Uhlelo lomgwaqo', 'nav.transactions': 'Imisebenzi', 'nav.myNodes': 'Ama-node ami', 'nav.profile': 'Iphrofayela', 'nav.settings': 'Izilungiselelo', 'nav.logout': 'Phuma', 'nav.workspace': 'Indawo yokusebenza', 'common.loading': 'Kuyalayishwa...', 'common.save': 'Londoloza', 'common.saving': 'Kuyalondolozwa...', 'common.cancel': 'Khansela', 'common.copy': 'Kopisha', 'common.copied': 'Kukopishiwe', 'common.fullName': 'Igama eligcwele', 'common.emailAddress': 'Ikheli le-imeyili', 'common.password': 'Iphasiwedi', 'common.confirmPassword': 'Qinisekisa iphasiwedi', 'profile.accountOverview': 'Uhlolojikelele lwe-akhawunti', 'profile.personalInformation': 'Ulwazi lomuntu siqu', 'profile.currentEmail': 'I-imeyili yamanje', 'profile.verified': 'Kuqinisekisiwe', 'profile.notVerified': 'Akuqinisekisiwe', 'profile.changeEmail': 'Shintsha ikheli le-imeyili', 'profile.newEmail': 'Ikheli le-imeyili elisha', 'profile.currentPassword': 'Iphasiwedi yamanje', 'profile.sendConfirmation': 'Thumela isiqinisekiso', 'profile.addPhoto': 'Engeza isithombe', 'profile.changePhoto': 'Shintsha isithombe', 'profile.removePhoto': 'Susa isithombe', 'profile.referralId': 'I-ID yokudlulisela', 'settings.appearance': 'Ukubukeka', 'settings.sound': 'Umsindo', 'settings.soundEffects': 'Imisindo yokusebenzelana', 'settings.volume': 'Izinga lomsindo', 'settings.notifications': 'Izaziso', 'settings.security': 'Ukuphepha', 'settings.twoFactor': 'Ukuqinisekiswa kwezinto ezimbili', 'settings.enableTwoFactor': 'Vumela ukuqinisekiswa kwezinto ezimbili', 'settings.disableTwoFactor': 'Khubaza ukuqinisekiswa kwezinto ezimbili', 'settings.recoveryCodes': 'Amakhodi okubuyisela', 'settings.language': 'Ulimi', 'settings.currency': 'Imali', 'settings.dark': 'Kumnyama', 'settings.light': 'Kukhanya', 'settings.system': 'Okwesistimu' },
}

const editProfileTranslations: Partial<Record<Exclude<LanguageCode, 'en'>, string>> = {
  fr: 'Modifier le profil', es: 'Editar perfil', pt: 'Editar perfil', de: 'Profil bearbeiten', it: 'Modifica profilo',
  nl: 'Profiel bewerken', ru: 'Изменить профиль', uk: 'Редагувати профіль', pl: 'Edytuj profil', tr: 'Profili düzenle',
  ar: 'تعديل الملف الشخصي', 'zh-CN': '编辑个人资料', 'zh-TW': '編輯個人資料', ja: 'プロフィールを編集', ko: '프로필 편집',
  hi: 'प्रोफ़ाइल संपादित करें', id: 'Edit profil', vi: 'Chỉnh sửa hồ sơ', th: 'แก้ไขโปรไฟล์', bn: 'প্রোফাইল সম্পাদনা',
  ro: 'Editează profilul', el: 'Επεξεργασία προφίλ', sk: 'Upraviť profil', zu: 'Hlela iphrofayela',
}
const resources = Object.fromEntries(languages.map(({ code }) => [code, { translation: code === 'en' ? english : {
  ...translated[code as Exclude<LanguageCode, 'en'>],
  ...(editProfileTranslations[code as Exclude<LanguageCode, 'en'>] ? { 'common.editProfile': editProfileTranslations[code as Exclude<LanguageCode, 'en'>] } : {}),
} }]))

function cachedLanguage(): LanguageCode {
  try {
    const preferences = JSON.parse(localStorage.getItem('nodeconnect_preferences') || '{}') as { language?: string }
    return languages.some((language) => language.code === preferences.language) ? preferences.language as LanguageCode : 'en'
  } catch {
    return 'en'
  }
}

export function languageDirection(language: string): 'ltr' | 'rtl' {
  return languages.find((item) => item.code === language)?.direction || 'ltr'
}

export const i18n = i18next
void i18n.use(initReactI18next).init({
  resources,
  lng: cachedLanguage(),
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
})

i18n.on('languageChanged', (language) => {
  if (typeof document === 'undefined') return
  document.documentElement.lang = language
  document.documentElement.dir = languageDirection(language)
})

export function useAppTranslation(): (key: string) => string {
  const { t, i18n: instance } = useTranslation()
  return (key) => {
    if (import.meta.env.DEV && !instance.exists(key as TranslationKey, { lng: instance.language, fallbackLng: false })) {
      return `⟦${key}⟧`
    }
    return t(key as TranslationKey)
  }
}